export interface Person {
    id?: number; // Optional for new entries (autogenerated by backend)
    fullName: string;
    email: string;
    address: string;
    city: string;
    state: string;
    zipCode: string;
    phone: string;
  }
  